Add require_relatives to hotel.rb
Previously this code produced the following results:
$ pry -r ./lib/hotel.rb
[1] pry(main)> h = Hotel::Hotel.new
=> #<Hotel::Hotel:0x00007ff6190d1b98>
[2] pry(main)> h.build_block(3, '2019-4-1', '2019-4-7', 150)
NameError: uninitialized constant Hotel::Hotel::RoomBlock
from /Users/droberts/Ada/AdaGold/hotel/lib/hotel.rb:74:in `build_block'

Now it works

Tests ran because `spec_helper.rb` required all of the lib files